
export const buildings = [
  { id: "farm",
    name: "Farm",
    image: null, // "assets/images/buildings/farm.png",
    type: 'unitProduction',
    reqHeroLevel: 0,
    level: 0, 
    goldCost: 10,
    gemCost: 0,
    goldIncomePerHit: 1,
    gemPerSecond: 0,
    upgradedClasses: { id: "fighter"}, 
    buildingRequired: null},
  { id: "mine",
    name: "Mine",
    image: null, // "assets/images/buildings/mine.png",
    type: 'economy',
    reqHeroLevel: 0,
    level: 0, 
    goldCost: 100,
    goldIncomePerHit: 2,
    gemCost: 0,
    gemPerSecond: 0,
    buildingRequired: { id: "farm", level: 1 }
    },
  { id: "lumberMill",
    name: "Lumber Mill", 
    image: null, // "assets/images/buildings/lumbermill.png",
    type: 'economy',
    reqHeroLevel: 0,
    level: 0,
    goldCost: 200,
    gemCost: 0,
    goldIncomePerHit: 3,
    gemPerSecond: 0,
    buildingRequired: { id: "mine", level: 1 },
  },
  { id: "inn",
    name: "Inn", 
    image: "assets/images/buildings/inn.webp",
    type: 'economy',
    reqHeroLevel: 0,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 6,
    gemPerSecond: 0,
    upgradedClasses: null,
    buildingRequired: { id: "farm", level: 1 }
  },
  { id: "gemMine",
    name: "Gem Mine", 
    image: null, //"assets/images/buildings/gemmine.png",
    type: 'economy',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 0,
    //gemPerSecond: 0.0167, // 1 gem per minute
    buildingRequired: { id: "mine", level: 5 }
  },
  { id: "barracks",
    name: "Barracks", 
    image: null, // "assets/images/buildings/barracks.png",
    type: 'unitProduction',
    reqHeroLevel: 0,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "knight" },
    // Example of multiple requirements
    buildingRequired: [
      { id: "lumberMill", level: 1 },
      { id: "mine", level: 1 },
      { id: "farm", level: 1 } 
    ]
  },
  { id: "archery",
    name: "Archery", 
    image: null, // "assets/images/buildings/archery.png",
    type: 'unitProduction',
    reqHeroLevel: 0,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "archer"},
    buildingRequired: { id: "barracks", level: 1 }
  },
  { id: "trainingCenter",
    name: "Training Center", 
    image: null, // "assets/images/buildings/training.png",
    type: 'upgrade',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    // Example of multiple requirements
    buildingRequired: [
      { id: "barracks", level: 5 },
      { id: "archery", level: 5 }
    ]
  },
  {
    id: "blacksmith",
    name: "Blacksmith",
    image: "assets/images/buildings/blacksmith.png",
    type: 'upgrade',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 300,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    buildingRequired: [
      { id: 'trainingCenter', level: 5 }
    ]
  },
  {
    id: "labyrinth",
    name: "Labyrinth",
    type: 'unitProduction',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 300,
    gemCost: 0,
    goldIncomePerHit: 1,
    gemPerSecond: 0,
    upgradedClasses: { id: "minotaur"},
    buildingRequired: [
      { id: "barracks", level: 5 },
      { id: "mine", level: 5 },
      { id: "blacksmith", level: 5 }
    ]
  },
  { id: "mageGuild",
    name: "Mage Guild", 
    image: "assets/images/buildings/mageguild.png",
    type: 'unitProduction',
    reqHeroLevel: 3,
    level: 0,
    goldCost: 100,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "sorceress"},
    buildingRequired: [
      { id: "barracks", level: 1 },
      { id: "inn", level: 1 },
      { id: "gemMine", level: 1 }
    ]
  },
  {
    id: "library",
    name: "Library",
    image: null, // "assets/images/buildings/library.png",
    type: 'upgrade',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 450,
    buildingRequired: { id: "mageGuild", level: 1 },
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    description: "Unlocks new spell tiers for the spellbook.",
  },
  {
    id: "dungeonShrine",
    name: "Dungeon Shrine",
    image: null, // "assets/images/buildings/dungeonShrine.png",
    type: 'upgrade',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 450,
    buildingRequired: [ 
      {id: "mageGuild", level: 1 },
      {id: "temple", level: 1 }
    ],
    dungeonProgressRequired: 10,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    description: "Unlocks random blessings.",
  },
  { id: "thievesGuild",
    name: "Thieves Guild", 
    image: null, // "assets/images/buildings/thievesguild.png",
    type: 'unitProduction',
    reqHeroLevel: 3,
    level: 0,
    goldCost: 200,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "rogue"},
    buildingRequired: { id: "barracks", level: 1 }
  },
  {
    id: "shadowGuild",
    name: "Shadow Guild",
    type: 'upgrade',
    image: null,
    reqHeroLevel: 5,
    level: 0,
    goldCost: 300,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    buildingRequired: [
      { id: 'thievesGuild', level: 5 },
      { id: 'blacksmith', level: 5}
    ]
  },
  { id: "temple",
    name: "Temple", 
    image: null, // "assets/images/buildings/temple.png",
    type: 'unitProduction',
    reqHeroLevel: 3,
    level: 0,
    goldCost: 150,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "cleric"},
    buildingRequired: { id: "barracks", level: 1 }
  },
  {
    id: "bellTower",
    name: "Bell Tower",
    image: null, // "assets/images/buildings/belltower.png",
    type: 'unitProduction',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 180,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "templar"},
    buildingRequired: { id: "temple", level: 1 },
  },
  { id: "grove",
    name: "Grove",
    image: null, // "assets/images/buildings/grove.png",
    type: 'unitProduction',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 200,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "druid"},
    // Example of multiple requirements (as array)
    buildingRequired: [
      { id: "lumberMill", level: 5 },
      { id: "temple", level: 1 },
      { id: "mageGuild", level: 5 }
    ]
  },
  {
    id: "graveyard",
    name: "Graveyard",
    type: 'upgrade',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 300,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    description: "Increases summon duration, higher tier summon rates, and summon attack power",
    buildingRequired: [
      { id: "farm", level: 5 },
      { id: "inn", level: 1 },
      { id: "temple", level: 1 }
    ],
    effects: [
      { type: "summonDuration", value: 2 }, // +2 seconds per level
      { type: "summonAttack", value: 0.05 },  // +0.05 attack per level
      { type: "summonRarity", value: 0.01 }  // +1% rare, +0.5% legendary per level
    ]
  },
  { id: "darkTower",
    name: "Dark Tower",
    image: null, // "assets/images/buildings/darktower.png",
    type: 'unitProduction',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 200,
    gemCost: 0,
    goldIncomePerHit: 0,
    gemPerSecond: 0,
    upgradedClasses: { id: "necromancer"},
    // Example of multiple requirements (as array)
    buildingRequired: [
      { id: "mageGuild", level: 1 },
      { id: "temple", level: 1 },
      { id: "graveyard", level: 1 }
    ]
  },
  {
  id: "nighonTunnels",
    name: "Nighon Tunnels",
    type: 'unitProduction',
    reqHeroLevel: 5,
    level: 0,
    goldCost: 400,
    gemCost: 0,
    goldIncomePerHit: 1,
    gemPerSecond: 0,
    upgradedClasses: { id: "warlock"},
    buildingRequired: [
      { id: "labyrinth", level: 5 },
      { id: "darkTower", level: 5 },
      { id: "grove", level: 5 }
    ]
  },
  { id: "castle",
    name: "Castle",
    type: 'economy',
    image: null, // "assets/images/buildings/castle.png",
    reqHeroLevel: 20,
    level: 0,
    goldCost: 1500,
    gemCost: 50,
    goldIncomePerHit: 10,
    gemPerSecond: 0, // 2 gems per minute
    // Example of many requirements (as array)
    buildingRequired: [
      { id: "farm", level: 20 },
      { id: "mine", level: 20 },
      { id: "lumberMill", level: 20 },
      { id: "barracks", level: 10 },
      { id: "archery", level: 10 },
      { id: "thievesGuild", level: 10 },
      { id: "temple", level: 10 },
      { id: "mageGuild", level: 10 },
    ]
    },
    { id: "fountain",
      name: "Fountain of Mirth",
      image: "assets/images/buildings/fountain.webp",
      type: 'upgrade',
      reqHeroLevel: 20,
      level: 0,
      goldCost: 1000,
      gemCost: 100,
      goldIncomePerHit: 0,
      gemPerSecond: 0.0501, // 3 gems per minute
      // Example of single requirement (as object)
      buildingRequired: { id: "castle", level: 1 }
    }
];
